language: node_js
node_js:
  - "10.16.0"
install:
  - npm install -g firebase-tools
  - npm install
script:
  - echo "Deploy!!"
  - npm run build
after_success:
  - firebase deploy --project g-to-k --token $FIREBASE_TOKEN