export const SET_SUBSCRIPTION_PLANS = "SET_SUBSCRIPTION_PLANS";
export const SEARCH_USERS = "SEARCH_USERS";
export const SET_USER = "SET_USER";
export const SET_DB_USER = "SET_DB_USER";
export const SET_LOGGED_IN = "SET_LOGGED_IN";
export const SET_RELOAD = "SET_RELOAD";

export const SET_CHAT_MESSAGES = "SET_CHAT_MESSAGES";
export const SET_CONVOS = "SET_CONVOS";

export const SET_SURVEYS_LIST = "SET_SURVEYS_LIST";

export const GET_ALERTS = "GET_ALERTS";
export const SET_ALERTS = "SET_ALERTS";
export const SET_NEW_ALERTS_COUNT = "SET_NEW_ALERTS_COUNT";

export const SET_NEW_MESSAGES_COUNT = "SET_NEW_MESSAGES_COUNT";